












































































class MAV_titleNavigation { idd = 52009; onLoad = "['navigation\gui', 'MAV_titleNavigation', _this] call MAV_gui_fnc_initLayer"; duration = 10e+9; fadeIn = 0; fadeOut = 0; 


class ControlsBackground { class Background: MAV_ctrlStaticBackground { x = (safeZoneX + safeZoneW) - ((100 + SIZE_M) * GRID_W); y = (safeZoneY + safeZoneH) - ((60 + SIZE_S) * GRID_H); w = 100 * GRID_W; h = 60 * GRID_H; }; class Map: MAV_ctrlMapEmpty { idc = 0x01; x = (safeZoneX + safeZoneW) - ((100 + SIZE_M) * GRID_W); y = (safeZoneY + safeZoneH) - ((60 + SIZE_S) * GRID_H); w = (100 - (100 / 5)) * GRID_W; h = (60 - SIZE_M) * GRID_H; colorBackground[] = {1,1,1,0}; colorOutside[] = {1,1,1,0}; colorTracks[] = {1, 1, 1, 1}; colorTracksFill[] = {1, 1, 1, 1}; colorRoads[] = {1, 1, 1, 1}; colorRoadsFill[] = {1, 1, 1, 1}; colorMainRoads[] = {1, 1, 1, 1}; colorMainRoadsFill[] = {1, 1, 1, 1}; ptsPerSquareSea = 5; ptsPerSquareTxt = 20; ptsPerSquareCLn = 10; ptsPerSquareExp = 10; ptsPerSquareCost = 10; ptsPerSquareFor = 9; ptsPerSquareForEdge = 9; ptsPerSquareRoad = 6; ptsPerSquareObj = 9; scaleMin = 0.0001; scaleMax = 1.0; scaleDefault = 0.1; alphaFadeStartScale = 0; alphaFadeEndScale = 0; text = "#(argb,8,8,3)color(1,1,1,1)"; sizeEx = 0; font = FONT_NORMAL; colorText[] = {0,0,0,0}; }; }; class Controls { class BottomText: MAV_ctrlStaticTitle { idc = 0x02; x = (safeZoneX + safeZoneW) - ((100 + SIZE_M) * GRID_W); y = (safeZoneY + safeZoneH) - ((60 + SIZE_S - (60 - SIZE_M)) * GRID_H); w = 100 * GRID_W; h = SIZE_M * GRID_H; shadow = 1; size = SIZE_M * GRID_H; sizeEx = SIZE_M * GRID_H; text = dialogCalculating; }; class DirectionIndicatorAhead: MAV_ctrlStaticPictureKeepAspect { idc = 0x05; x = (safeZoneX + safeZoneW) - ((100 + SIZE_M - (100 - 14)) * GRID_W); y = (safeZoneY + safeZoneH) - ((60 + SIZE_S - 16 - 2) * GRID_H); w = 7 * GRID_W; h = 7 * GRID_H; text = "maverick
avigation\data\arrow-left.paa"; }; class BackgroundDirectionIndicator: MAV_ctrlStaticBackground { idc = 0x06;
x = (safeZoneX + safeZoneW) - ((100 + SIZE_M - (100 - 20)) * GRID_W); y = (safeZoneY + safeZoneH) - ((60 + SIZE_S - 25 - 2) * GRID_H); w = (100 / 5) * GRID_W; h = 28 * GRID_H; colorBackground[] = {0.99,0.49,0,0}; }; class DirectionIndicator: MAV_ctrlStaticPictureKeepAspect { idc = 0x03; x = (safeZoneX + safeZoneW) - ((100 + SIZE_M - (100 - 18)) * GRID_W); y = (safeZoneY + safeZoneH) - ((60 + SIZE_S - 28 - 2) * GRID_H); w = 15 * GRID_W; h = 15 * GRID_H; text = "maverick
avigation\data\arrow-straight.paa"; colorText[] = {1,1,1,1}; }; class DirectionInformation: MAV_ctrlStructuredText { idc = 0x04; x = (safeZoneX + safeZoneW) - ((100 + SIZE_M - (100 - 20)) * GRID_W); y = (safeZoneY + safeZoneH) - ((60 + SIZE_S - 45 - 2) * GRID_H); w = (100 / 5) * GRID_W; h = SIZE_M * GRID_W; text = "XXXm"; size = SIZE_M * GRID_H; sizeEx = SIZE_M * GRID_H; shadow = 0; colorText[] = {1,1,1,1}; }; class ETAInformation: MAV_ctrlStaticTitle { idc = 0x07; x = (safeZoneX + safeZoneW) - ((100 + SIZE_M - (100 - 20)) * GRID_W); y = (safeZoneY + safeZoneH) - ((60 + SIZE_S - 1) * GRID_H); w = (100 / 5) * GRID_W; h = SIZE_M * GRID_H; text = "X min"; }; class DistanceInformation: MAV_ctrlStaticTitle { idc = 0x08; x = (safeZoneX + safeZoneW) - ((100 + SIZE_M - (100 - 20)) * GRID_W); y = (safeZoneY + safeZoneH) - ((60 + SIZE_S - 7) * GRID_H); w = (100 / 5) * GRID_W; h = SIZE_M * GRID_H; text = "XXX m"; }; class BackgroundWarningSignInformation: MAV_ctrlStaticBackground { idc = 0xA; x = (safeZoneX + safeZoneW) - ((100 + SIZE_M - 1) * GRID_W); y = (safeZoneY + safeZoneH) - ((60 + SIZE_S - 1) * GRID_H); w = 13 * GRID_W; h = 13 * GRID_H; colorBackground[] = {0,0,0,0}; }; class WarningSignInformation: MAV_ctrlStructuredText { idc = 0x09; x = (safeZoneX + safeZoneW) - ((100 + SIZE_M - 0.5) * GRID_W); y = (safeZoneY + safeZoneH) - ((60 + SIZE_S - 2.5) * GRID_H); w = (100 - 20) * GRID_W; h = 11 * GRID_H; size = 10 * GRID_H; sizeEx = 10 * GRID_H; shadow = 0; color[] = {0,0,0,1}; }; }; };

