
















































































































































































































































































disableSerialization; params [ ["_mode", "", [""]], ["_params", [], [[]]] ]; switch _mode do { case "onLoad": { _params params [ ["_display", displayNull, [displayNull]] ]; MAV_guiNavigationSaved_Spam = diag_tickTime; private _world = worldName; private _close = _display displayCtrl 0x04; _close ctrlAddEventHandler ["ButtonClick", {ctrlParent (_this select 0) closeDisplay 0;}]; private _start = _display displayCtrl 0x02; _start ctrlAddEventHandler ["ButtonClick", {["start", _this] call MAV_guiNavigationSaved}]; private _delete = _display displayCtrl 0x03; _delete ctrlAddEventHandler ["ButtonClick", {["delete", _this] call MAV_guiNavigationSaved}]; private _list = _display displayCtrl 0x01; _list ctrlAddEventHandler ["LBSelChanged", {["routeSelected", _this] call MAV_guiNavigationSaved}]; { private _nr = _x; private _ret = profileNamespace getVariable [format ["MAV_gps_saved_%1_%2", _world, _nr], []]; if (!(_ret isEqualTo []) && {_ret isEqualTypeParams ["", [], []]}) then { _ret params ["_title", "_points", "_route"]; private _index = _list lbAdd _title; _list lbSetValue [_index, _nr]; _list lbSetData [_index, _title]; }; } forEach [0, 1, 2, 3, 4]; if (lbSize _list isEqualTo 0) exitWith { _list lbAdd (getText(missionConfigFile >> "maverick_navigation_cfg" >> "localization" >> "msgNoSavedRoutes")); }; }; case "routeSelected": { _params params [ ["_ctrl", controlNull, [controlNull]], ["_index", -1, [0]] ]; private _display = ctrlParent _ctrl; private _start = _display displayCtrl 0x02; if (_index isEqualTo -1) exitWith { _start ctrlShow false; (_display displayCtrl 0x03) ctrlShow false; }; _start ctrlShow (isNil "MAV_gps_currentRoute" && {!((_ctrl lbData _index) isEqualTo "")}); private _delete = _display displayCtrl 0x03; _delete ctrlShow !((_ctrl lbData _index) isEqualTo ""); }; case "start": { if !(isNil "MAV_gps_v_currentRoute") exitWith { (getText(missionConfigFile >> "maverick_navigation_cfg" >> "localization" >> "msgFinishRouteFirst")) call zero_fnc_msg;
}; if (MAV_guiNavigationSaved_Spam > diag_tickTime) exitWith {}; MAV_guiNavigationSaved_Spam = diag_tickTime + 0.5; _params params [ ["_ctrl", controlNull, [controlNull]] ]; private _display = ctrlParent _ctrl; private _list = _display displayCtrl 0x01; private _curSel = lbCurSel _list; if (_curSel isEqualTo -1) exitWith {}; (profileNamespace getVariable [format ["MAV_gps_saved_%1_%2", toLower worldName, _list lbValue _curSel], []]) params [ ["_title", "", [""]], ["_points", [], [[]]], ["_route", [], [[]]], ["_searchType", "default", [""]] ]; _route = _route apply {(_x nearRoads 0.5) param [0]}; _route = _route select {!isNull _x}; _startRoad = if !((_points param [0]) isEqualTo []) then { [_points param [0], 100, []] call BIS_fnc_nearestRoad } else { objNull }; _middleRoad = if !((_points param [1]) isEqualTo []) then { [_points param [1], 100, []] call BIS_fnc_nearestRoad } else { objNull }; _endRoad = if !((_points param [2]) isEqualTo []) then { [_points param [2], 100, []] call BIS_fnc_nearestRoad } else { objNull }; mav_gps_v_currentRouteSearchType = _searchType; MAV_guiNavigationNew_info = [_startRoad, _middleRoad, _endRoad, _route]; MAV_guiNavigationCalculate_Route = _route; _display createDisplay "MAV_guiNavigationCalculateWO"; }; case "delete": { if (MAV_guiNavigationSaved_Spam > diag_tickTime) exitWith {}; MAV_guiNavigationSaved_Spam = diag_tickTime + 0.5; _params params [ ["_ctrl", controlNull, [controlNull]] ]; private _display = ctrlParent _ctrl; private _list = _display displayCtrl 0x01; private _curSel = lbCurSel _list; if !(_curSel isEqualTo -1) then { _list lbDelete _curSel; profileNamespace setVariable [format ["MAV_gps_saved_%1_%2", worldName, _list lbValue _curSel], nil]; [(getText(missionConfigFile >> "maverick_navigation_cfg" >> "localization" >> "msgRouteDeleted")),1] call zero_fnc_msg; saveProfileNamespace; }; if (lbSize _list isEqualTo 0) then { _ctrl ctrlShow false; (_display displayCtrl 0x02) ctrlShow false; _list lbAdd (getText(missionConfigFile >> "maverick_navigation_cfg" >> "localization" >> "msgNoSavedRoutes")); }; _list lbSetCurSel -1; }; case "onUnload": { MAV_guiNavigationSaved_Spam = nil; }; };
