if (!hasInterface) exitWith {}; private["_display","_title","_playerListTitle","_gangPlayerListTitle","_playerList","_gangPlayerList","_description","_group","_gang","_buttonRank","_buttonNachfolger","_buttonUpgrade","_member","_rang","_index","_name","_data","_uid","_buttonOffline","_unit"]; if(isNil "zero_var_gangMemberAdd") then {zero_var_gangMemberAdd = [];}; if(isNil "zero_var_gangMemberRemove") then {zero_var_gangMemberRemove = [];}; if(isNil "zero_var_gangMemberChangeRank") then {zero_var_gangMemberChangeRank = [];}; _group = (group player); _gang = _group getVariable ["zero_var_gang",[]]; if(_gang isEqualTo []) exitWith {"Du bist in keiner Gang" call zero_fnc_msg;}; if(count _gang < 7) exitWith {"Es ist ein Fehler aufgetreten" call zero_fnc_msg;}; uiSleep random(0.75); if(!isNull (_group getVariable["zero_var_gangMemberInUse",objNull])) exitWith {"Auf die Mitgliederverwaltung wird bereits zugegriffen!" call zero_fnc_msg;}; _group setVariable["zero_var_gangMemberInUse",player,true]; createDialog "zero_var_gangmember"; disableSerialization; _display = findDisplay 3400; if (isNull _display) exitWith {}; _title = _display displayCtrl 3401; _playerListTitle = _display displayCtrl 3402; _gangPlayerListTitle = _display displayCtrl 3403; _playerList = _display displayCtrl 3404; _gangPlayerList = _display displayCtrl 3405; _description = _display displayCtrl 3406; _buttonRank = _display displayCtrl 3407; _buttonNachfolger = _display displayCtrl 3408; _buttonUpgrade = _display displayCtrl 3409; _buttonOffline = _display displayCtrl 3411; _title ctrlSetStructuredText parseText format["<t align='center' size='1.5'>Mitglieder Managementsystem</t>"]; _playerListTitle ctrlSetStructuredText parseText format["<t align='center' size='1.25'>Spielerliste</t>"]; _description ctrlSetStructuredText parseText format[ "<t size='0.9'>
	<t underline=true>Steuerung:</t><br/>
	<t underline=true>Einladen</t>: Doppelklick auf den Spieler in der Spielerliste<br/>
	<t underline=true>Entfernen</t>: Doppelklick auf den Spieler in der Gangmitgliederliste<br/>
	<t underline=true>Rangänderung</t>: Spieler auswählen und auf <t color='#ffff00'>Rangänderung</t> klicken<br/>
	<t underline=true>Nachfolger</t>: Spieler auswählen und auf <t color='#ffff00'>Nachfolger</t> klicken<br/>
	<t underline=true>Upgrade</t>: Erhöht die maximale Memberanzahl<br/>
	<t underline=true>Offline Member</t>: Offline Member kicken<br/>
	<t underline=true>Änderung übernehmen</t>: Spieler werden eingeladen/gekickt und<br/> Rangänderungen werden übernommen<br/>
	</t>" ];
if(typeName (_gang select(count _gang -1)) == "BOOL") then { _buttonRank ctrlEnable false; _buttonOffline ctrlEnable false; }; if((getPlayerUID player) != (_gang select 2)) then {_buttonNachfolger ctrlEnable false;}; _member = _gang select 3; _rang = 0; _index = [getPlayerUID player, _member] call zero_fnc_findIndex; if(_index != -1) then { _rang = (_member select _index) select 1; }; if(_rang < 3) then { _buttonRank ctrlEnable false; _buttonOffline ctrlEnable false; _buttonNachfolger ctrlEnable false; _buttonUpgrade ctrlEnable false; }; lbClear _playerList; lbClear _gangPlayerList; { if (_x != player && !(_x in units(group player)) && !(getPlayerUID _x in zero_var_gangMemberAdd) && ((((side _x)) isEqualTo civilian) || (((side _x)) isEqualTo opfor))) then { _playerList lbAdd format["%1",_x getVariable["zero_var_realname",name _x]]; _playerList lbSetData [(lbSize _playerList)-1,str(_x)]; }; } forEach playableUnits; lbSort _playerList; { _name = _x getVariable["zero_var_realname",name _x]; _index = [getPlayerUID _x,_member] call zero_fnc_findIndex; if(_index != -1) then { _rang = (_member select _index) select 1; }; _gangPlayerList lbAdd format["%1 [%2]",_name,_rang]; _gangPlayerList lbSetData [(lbSize _gangPlayerList)-1,str(_x)]; } forEach units(group player); { _unit = _x select 0; _unit = call compile _unit; _data = _x select 1; _uid = _data select 0; if(!(_unit in units(group player))) then { _rang = _data select 1; _name = _data select 2; _gangPlayerList lbAdd format["%1 [%2]",_name,_rang]; _gangPlayerList lbSetData [(lbSize _gangPlayerList)-1,str(_unit)]; }; } forEach zero_var_gangMemberAdd; lbSort _gangPlayerList; _gangPlayerListTitle ctrlSetStructuredText parseText format["<t align='center' size='1.25'>Gangmitglieder %1/%2</t>",lbSize _gangPlayerList, _gang select 4]; ["Änderung werden erst durch Klick auf -Übernehmen- angewendet!",1] call zero_fnc_msg; waitUntil {isNull _display}; zero_var_gangMemberAdd = nil; zero_var_gangMemberRemove = nil; zero_var_gangMemberChangeRank = nil; zero_var_gangOfflineKick = nil; (group player) setVariable["zero_var_gangMemberInUse",nil,true];
