if (!hasInterface) exitWith {}; private _box = param [1, objNull, [objNull]]; if (isNull _box) exitWith { true; }; 

0 spawn zero_fnc_checkInventory; private _rank = player getVariable ["zero_var_rank", 0]; if (_box isKindOf "LandVehicle" || _box isKindOf "Air" || _box isKindOf "Ship" || _box isKindOf "CargoNet_01_ammo_base_F" || _box isKindOf "ReammoBox_F" || _box isKindOf "GroundWeaponHolder") exitWith { if (locked _box isEqualTo 2 && (zero_var_playerSide != west || zero_var_playerSide isEqualTo west && _rank < 2)) exitWith { 0 spawn { for "_i" from 1 to 10 do { closeDialog 0; uiSleep 0.1; }; if(!isNull (findDisplay 602)) then { closeDialog 0; closeDialog 0; }; }; (localize "STR_MISC_VehInventory") spawn zero_fnc_msg; true; }; _box spawn { 

if(!((serverTime - zero_var_vehicleTrunkCooldown) > 5)) exitWith {"Du kannst nur alle 5 Sekunden auf das Inventar zugreifen!" call zero_fnc_msg; 0 spawn { for "_i" from 1 to 10 do { closeDialog 0; uiSleep 0.1; }; if(!isNull (findDisplay 602)) then { closeDialog 0; closeDialog 0; }; };}; uiSleep random( 1 ); zero_var_vehicleTrunkCooldown = serverTime; if (((_this getVariable["zero_var_antiDupe", [player, (netId player)]]) select 0) != player && {!isNull (objectFromNetId ((_this getVariable["zero_var_antiDupe", [player, (netId player)]]) select 1))}) exitWith { 0 spawn { for "_i" from 1 to 10 do { closeDialog 0; uiSleep 0.1; }; if(!isNull (findDisplay 602)) then { closeDialog 0; closeDialog 0; }; }; (format ["%1 greift bereits auf das Inventar zu!", (_this getVariable ["zero_var_antiDupe", [objNull,objNull]] select 0) getVariable ["zero_var_realname", ""]]) spawn zero_fnc_msg; true; }; uiSleep random( 1 ); if (((_this getVariable["zero_var_antiDupe", [player, (netId player)]]) select 0) != player && {!isNull (objectFromNetId ((_this getVariable["zero_var_antiDupe", [player, (netId player)]]) select 1))}) exitWith { 0 spawn { for "_i" from 1 to 10 do { closeDialog 0; uiSleep 0.1; }; if(!isNull (findDisplay 602)) then { closeDialog 0; closeDialog 0; }; }; (format ["%1 greift bereits auf das Inventar zu!", (_this getVariable ["zero_var_antiDupe", [objNull,objNull]] select 0) getVariable ["zero_var_realname", ""]]) spawn zero_fnc_msg;
true; }; uiSleep random( 1 ); if (((_this getVariable["zero_var_antiDupe", [player, (netId player)]]) select 0) != player && {!isNull (objectFromNetId ((_this getVariable["zero_var_antiDupe", [player, (netId player)]]) select 1))}) exitWith { 0 spawn { for "_i" from 1 to 10 do { closeDialog 0; uiSleep 0.1; }; if(!isNull (findDisplay 602)) then { closeDialog 0; closeDialog 0; }; }; (format ["%1 greift bereits auf das Inventar zu!", (_this getVariable ["zero_var_antiDupe", [objNull,objNull]] select 0) getVariable ["zero_var_realname", ""]]) spawn zero_fnc_msg; true; }; uiSleep random( 1 ); _this setVariable ["zero_var_antiDupe", [player, (netId player)], true]; zero_var_curBox = _this; _this spawn { 

uiSleep 1; while{!isNull (findDisplay 602)} do { if (((_this getVariable["zero_var_antiDupe", [player, (netId player)]]) select 0) != player && {!isNull (objectFromNetId ((_this getVariable["zero_var_antiDupe", [player, (netId player)]]) select 1))}) exitWith { 0 spawn { for "_i" from 1 to 10 do { closeDialog 0; uiSleep 0.1; }; if(!isNull (findDisplay 602)) then { closeDialog 0; closeDialog 0; }; }; (format ["%1 greift bereits auf das Inventar zu!", (_this getVariable ["zero_var_antiDupe", [objNull,objNull]] select 0) getVariable ["zero_var_realname", ""]]) spawn zero_fnc_msg; }; }; }; }; false; }; 

if ((getNumber (configFile >> "CfgVehicles" >> (typeOf _box) >> "isBackpack") isEqualTo 1) && zero_var_playerSide != west || (zero_var_playerSide isEqualTo west && (_rank < 2 || ((objectParent _box) getVariable["zero_var_rank", 0]) > _rank ))) exitWith { 0 spawn { for "_i" from 1 to 10 do { closeDialog 0; uiSleep 0.1; }; if(!isNull (findDisplay 602)) then { closeDialog 0; closeDialog 0; }; }; (localize "STR_MISC_Backpack") spawn zero_fnc_msg; true; }; if (_box isKindOf "Man" && !alive _box && (zero_var_playerSide != west || (zero_var_playerSide isEqualTo west && _rank < 2))) exitWith { 0 spawn { for "_i" from 1 to 10 do { closeDialog 0; uiSleep 0.1; }; if(!isNull (findDisplay 602)) then { closeDialog 0; closeDialog 0; }; }; (localize "STR_ISTR_AntiLootDeadBodies") spawn zero_fnc_msg; true; }; false;
