class RscDisplayTaxiCall { idd = MAV_IDD_RSCDISPLAYTAXICALL; onLoad = "['taxis\gui', 'RscDisplayTaxiCall', _this, true, 'RscDisplayTaxiCall'] call MAV_gui_fnc_openGUI"; 









class controlsBackground { class Background: MAV_ctrlStaticBackground { x = (CENTER_X - ((150 / 2) - (0) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (0) - (0)) * GRID_H); w = ((150) * GRID_W); h = ((90) * GRID_H); }; }; class Controls { class Header: MAV_ctrlStaticTitle { x = (CENTER_X - ((150 / 2) - (0) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (0) - (0)) * GRID_H); w = ((150) * GRID_W); h = ((6) * GRID_H); text = dialogCallTaxiTitle; moving = 0; }; class DestinationMap: MAV_ctrlMap { idc = MAV_IDC_RSCDISPLAYTAXICALL_DESTINATIONMAP; x = (CENTER_X - ((150 / 2) - (1.5) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (6 + 1.5) - (0)) * GRID_H); w = ((90) * GRID_W); h = ((90 - 6 - 1.5 * 2 - 8) * GRID_H); }; 

class DestinationHeader: MAV_ctrlStaticTitle { x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (6 + 1.5) - (0)) * GRID_H); w = (((150 - 1.5 * 3 - 90)) * GRID_W); h = ((SIZE_M) * GRID_H); text = dialogDestination; moving = 0; }; class DestinationExplanationText: MAV_ctrlStaticMulti { x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (6 + 1.5 + 1.5 + SIZE_M) - (0)) * GRID_H); w = (((150 - 1.5 * 3 - 90)) * GRID_W); h = ((20) * GRID_H); text = dialogHowToDestination; }; class StatusHeader: MAV_ctrlStaticTitle { x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (6 + 1.5 * 3 + SIZE_M + 20) - (0)) * GRID_H); w = (((150 - 1.5 * 3 - 90)) * GRID_W); h = ((SIZE_M) * GRID_H); text = dialogStatusTitle; moving = 0; }; class AvailableDriversHeader: MAV_ctrlStaticTitle { x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (90 - 8 - 1.5 - SIZE_M) - (0)) * GRID_H); w = (((150 - 1.5 * 3 - 90)) * GRID_W); h = ((SIZE_M) * GRID_H); text = dialogAvaibleDrivers; moving = 0; }; class AvailableDriversNumber: MAV_ctrlStatic { idc = MAV_IDC_RSCDISPLAYTAXICALL_AVAILABLEDRIVERS; style = ST_RIGHT; x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (90 - 8 - 1.5 - SIZE_M) - (0)) * GRID_H); w = (((150 - 1.5 * 3 - 90)) * GRID_W); h = ((SIZE_M) * GRID_H); text = ""; shadow = 0; }; class CB1: MAV_ctrlCheckbox { idc = MAV_IDC_RSCDISPLAYTAXICALL_STATUS_MARKEDDESTINATION; x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (6 + 1.5 * 4 + SIZE_M * 2 + 20) - (0)) * GRID_H); w = ((SIZE_M) * GRID_W); h = ((SIZE_M) * GRID_H); }; class CB1Text: MAV_ctrlStatic { x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5 + SIZE_M) - (0)) * GRID_W);
y = (CENTER_Y - ((90 / 2) - (6 + 1.5 * 4 + SIZE_M * 2 + 20) - (0)) * GRID_H); w = (((150 - 1.5 * 3 - 90) - SIZE_M) * GRID_W); h = ((SIZE_M) * GRID_H); text = dialogStatusMarkedDest; }; class CB2: MAV_ctrlCheckbox { idc = MAV_IDC_RSCDISPLAYTAXICALL_STATUS_CREATEDCALL; x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (6 + 1.5 * 4 + SIZE_M * 2 + 20 + (SIZE_M + 1.5) * 1) - (0)) * GRID_H); w = ((SIZE_M) * GRID_W); h = ((SIZE_M) * GRID_H); }; class CB2Text: MAV_ctrlStatic { x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5 + SIZE_M) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (6 + 1.5 * 4 + SIZE_M * 2 + 20 + (SIZE_M + 1.5) * 1) - (0)) * GRID_H); w = (((150 - 1.5 * 3 - 90) - SIZE_M) * GRID_W); h = ((SIZE_M) * GRID_H); text = dialogStatusCreatedCall; }; class CB3: MAV_ctrlCheckbox { idc = MAV_IDC_RSCDISPLAYTAXICALL_STATUS_DRIVERFOUND; x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (6 + 1.5 * 4 + SIZE_M * 2 + 20 + (SIZE_M + 1.5) * 2) - (0)) * GRID_H); w = ((SIZE_M) * GRID_W); h = ((SIZE_M) * GRID_H); }; class CB3Text: MAV_ctrlStatic { x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5 + SIZE_M) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (6 + 1.5 * 4 + SIZE_M * 2 + 20 + (SIZE_M + 1.5) * 2) - (0)) * GRID_H); w = (((150 - 1.5 * 3 - 90) - SIZE_M) * GRID_W); h = ((SIZE_M) * GRID_H); text = dialogStatusDriverFound; }; class CB4: MAV_ctrlCheckbox { idc = MAV_IDC_RSCDISPLAYTAXICALL_STATUS_PICKEDUP; x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (6 + 1.5 * 4 + SIZE_M * 2 + 20 + (SIZE_M + 1.5) * 3) - (0)) * GRID_H); w = ((SIZE_M) * GRID_W); h = ((SIZE_M) * GRID_H); }; class CB4Text: MAV_ctrlStatic { x = (CENTER_X - ((150 / 2) - (1.5 + 90 + 1.5 + SIZE_M) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (6 + 1.5 * 4 + SIZE_M * 2 + 20 + (SIZE_M + 1.5) * 3) - (0)) * GRID_H); w = (((150 - 1.5 * 3 - 90) - SIZE_M) * GRID_W); h = ((SIZE_M) * GRID_H); text = dialogStatusPickedUp; }; class Footer: MAV_ctrlStaticFooter { 

x = (CENTER_X - ((150 / 2) - (0) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (90 - 8) - (0)) * GRID_H); w = ((150) * GRID_W); h = ((8) * GRID_H); }; class CloseDialog: MAV_ctrlButton { 


x = (CENTER_X - ((150 / 2) - (1.5) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (90 - 1.5 - 5) - (0)) * GRID_H); w = ((30) * GRID_W); h = ((5) * GRID_H); text = dialogClose; onButtonClick = "closeDialog 0;"; }; class CallTaxiButton: MAV_ctrlButton { 


idc = MAV_IDC_RSCDISPLAYTAXICALL_CALLTAXI; x = (CENTER_X - ((150 / 2) - (150 - 1.5 - 50) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (90 - 1.5 - 5) - (0)) * GRID_H); w = ((50) * GRID_W); h = ((5) * GRID_H); text = dialogCallTaxi; show = 0; }; class CancelTaxiButton: MAV_ctrlButton { 


idc = MAV_IDC_RSCDISPLAYTAXICALL_CANCELTAXI; x = (CENTER_X - ((150 / 2) - (150 - 1.5 - 50) - (0)) * GRID_W); y = (CENTER_Y - ((90 / 2) - (90 - 1.5 - 5) - (0)) * GRID_H); w = ((50) * GRID_W); h = ((5) * GRID_H); text = dialogCancelTaxi; show = 0; }; }; };
