










































disableSerialization; params [ ["_mode", "", [""]], ["_params", [], [[]]] ]; switch (_mode) do { case "onLoad": { _params params [ ["_display", displayNull, [displayNull]] ]; private _customizeTaximeterPositionButton = _display displayCtrl 11; _customizeTaximeterPositionButton ctrlAddEventHandler ["ButtonClick", {["customizeTaximeter", _this] call RscDisplayTaxiSettings}]; private _customizeTaximeterPositionResetButton = _display displayCtrl 12;
_customizeTaximeterPositionResetButton ctrlAddEventHandler ["ButtonClick", {["resetTaximeter", _this] call RscDisplayTaxiSettings}]; }; case "customizeTaximeter": { _params params [ ["_btnCtrl", controlNull, [controlNull]] ]; private _display = ctrlParent _btnCtrl; createDialog "RscDisplayTaxiCustomizeTaximeter"; }; case "resetTaximeter": { _params params [ ["_btnCtrl", controlNull, [controlNull]] ]; private _display = ctrlParent _btnCtrl; profileNamespace setVariable ["mav_taxi_v_taximeterPosition", []]; saveProfileNamespace; hint (["msgTaximeterPositionReset"] call mav_taxi_fnc_getLocalization); }; };
