sounds[] = {}; class SirenLong { name = "SirenLong"; sound[] = {"\Resources\Sounds\Siren_Long.ogg", 20, 1}; titles[] = {}; }; class Yawalla { name = "Yawalla"; sound[] = {"\Resources\Sounds\Yawalla.ogg", 18, 1}; titles[] = {}; }; class CopYelp { name = "CopYelp"; sound[] = {"\Resources\Sounds\CopYelp.ogg", 19, 1}; titles[] = {}; }; class MedicSiren { name = "MedicSiren"; sound[] = {"\Resources\Sounds\MedicSiren.ogg", 16.2, 1}; titles[] = {}; }; class MedicYelp { name = "MedicYelp"; sound[] = {"\Resources\Sounds\MedicYelp.ogg", 16.2, 1}; titles[] = {}; }; class JoinSound { name = "JoinSound"; sound[] = {"\Resources\Sounds\join_sound.ogg", 1.0, 1}; titles[] = {}; }; class tazersound { name = "Tazersound"; sound[] = {"\Resources\Sounds\tazer.ogg", 0.25, 1}; titles[] = {}; }; class flashbang { name = "flashbang"; sound[] = {"\Resources\Sounds\flashbang.ogg", 1.0, 1}; titles[] = {}; }; class UnlockSound { name = "UnlockSound"; sound[] = {"\Resources\Sounds\unlock.ogg", 0.75, 1}; titles[] = {}; }; class LockSound { name = "LockSound"; sound[] = {"\Resources\Sounds\lock.ogg", 0.75, 1};
titles[] = {}; }; class car_alarm { name = "car_alarm"; sound[] = {"@A3\sounds_f\sfx\alarmCar.wss", 1.0, 1}; titles[] = {}; }; class open_chute { name = "open_chute"; sound[] = {"@A3\sounds_f\characters\parachute\parachute_open.wss", 10, 1}; titles[] = {}; }; class close_chute { name = "close_chute"; sound[] = {"@A3\sounds_f\characters\parachute\parachute_landing.wss", 10, 1}; titles[] = {}; }; class earplug { name = "earplug"; sound[] = {"\Resources\Sounds\earplug.ogg", 0.75, 1}; titles[] = {}; }; class join { name = "join"; sound[] = {"@A3\Music_F\music\LeadTrack01_F.ogg", 1.0, 1}; titles[] = {}; }; class join_2 { name = "join_2"; sound[] = {"@A3\Music_F\music\LeadTrack06_F.ogg", 1.0, 1}; titles[] = {}; }; class message { name = "message"; sound[] = { "@A3\sounds_f\sfx\beep_target.wss", 1, 1 }; titles[] = {}; }; class message_error { name = "message_error"; sound[] = { "@A3\sounds_f\sfx\hint-3.wss", 1, 1 }; titles[] = {}; }; 
class gpsvoice_female1_sound100mLeft { name = "gpsvoice_female1_sound100mLeft"; sound[] = {"\maverick
avigation\sounds\voicepacks\female_de-de_1\left_turn_100m.ogg", 4, 1}; titles[] = {}; }; class gpsvoice_female1_soundNowLeft { name = "gpsvoice_female1_soundNowLeft"; sound[] = {"\maverick
avigation\sounds\voicepacks\female_de-de_1\left_turn_now.ogg", 4, 1}; titles[] = {}; }; class gpsvoice_female1_sound100mRight { name = "gpsvoice_female1_sound100mRight"; sound[] = {"\maverick
avigation\sounds\voicepacks\female_de-de_1\right_turn_100m.ogg", 4, 1}; titles[] = {}; }; class gpsvoice_female1_soundNowRight { name = "gpsvoice_female1_soundNowRight"; sound[] = {"\maverick
avigation\sounds\voicepacks\female_de-de_1\right_turn_now.ogg", 4, 1};
titles[] = {}; }; class gpsvoice_female1_soundOnDestinationRoad { name = "gpsvoice_female1_soundOnDestinationRoad"; sound[] = {"\maverick
avigation\sounds\voicepacks\female_de-de_1\destination_road_reached.ogg", 4, 1}; titles[] = {}; }; class gpsvoice_female1_soundDestinationReached { name = "gpsvoice_female1_soundDestinationReached"; sound[] = {"\maverick
avigation\sounds\voicepacks\female_de-de_1\destination_reached.ogg", 4, 1}; titles[] = {}; }; class gpsvoice_female1_soundFollowRoad { name = "gpsvoice_female1_soundFollowRoad"; sound[] = {"\maverick
avigation\sounds\voicepacks\female_de-de_1\follow_road.ogg", 4, 1}; titles[] = {}; };

class gpsvoice_male1_sound100mLeft { name = "gpsvoice_male1_sound100mLeft"; sound[] = {"\maverick
avigation\sounds\voicepacks\male_de-de_1\left_turn_100m.ogg", 4, 1}; titles[] = {}; }; class gpsvoice_male1_soundNowLeft { name = "gpsvoice_male1_soundNowLeft"; sound[] = {"\maverick
avigation\sounds\voicepacks\male_de-de_1\left_turn_now.ogg", 4, 1}; titles[] = {}; }; class gpsvoice_male1_sound100mRight { name = "gpsvoice_male1_sound100mRight"; sound[] = {"\maverick
avigation\sounds\voicepacks\male_de-de_1\right_turn_100m.ogg", 4, 1}; titles[] = {}; }; class gpsvoice_male1_soundNowRight { name = "gpsvoice_male1_soundNowRight"; sound[] = {"\maverick
avigation\sounds\voicepacks\male_de-de_1\right_turn_now.ogg", 4, 1};
titles[] = {}; }; class gpsvoice_male1_soundOnDestinationRoad { name = "gpsvoice_male1_soundOnDestinationRoad"; sound[] = {"\maverick
avigation\sounds\voicepacks\male_de-de_1\destination_road_reached.ogg", 4, 1}; titles[] = {}; }; class gpsvoice_male1_soundDestinationReached { name = "gpsvoice_male1_soundDestinationReached"; sound[] = {"\maverick
avigation\sounds\voicepacks\male_de-de_1\destination_reached.ogg", 4, 1}; titles[] = {}; }; class gpsvoice_male1_soundFollowRoad { name = "gpsvoice_male1_soundFollowRoad"; sound[] = {"\maverick
avigation\sounds\voicepacks\male_de-de_1\follow_road.ogg", 4, 1}; titles[] = {}; };

