if (!hasInterface) exitWith {};
 private["_time","_firstCall","_uiDisp","_timer","_announce","_gangs","_marker"];
 _time = param[0,-1,[0]];
 _firstCall = param[1,false,[false]];
 if(_time isEqualTo -1) exitWith {systemChat "fn_gangEroberungTimer -1"};
 disableSerialization;
 _time = serverTime + (_time * 60);
 6 cutRsc ["zero_var_timer","PLAIN"];
 _uiDisp = uiNamespace getVariable "zero_var_timer";
 _timer = _uiDisp displayCtrl 38301;
 while {true} do { if(isNull _uiDisp) then { 6 cutRsc ["zero_var_timer","PLAIN"];
 _uiDisp = uiNamespace getVariable "zero_var_timer";
 _timer = _uiDisp displayCtrl 38301;
 };
 if(round(_time - serverTime) < 1) exitWith {};
 if(!alive player) exitWith {};
 _timer ctrlSetText format["%1",[(_time - serverTime),"MM:SS.MS"] call BIS_fnc_secondsToString];
 uiSleep 0.08;
 };
 6 cutText["","PLAIN"];
 if(!alive player) exitWith {};
 if(_firstCall) then { uiSleep random(1);
 if(!(zero_gang_flag getVariable["zero_var_gangFight",-1] > 0)) then { [[player, "zero_var_fnc_createMarker", ["gang_angriff",[21973.5,21081.1,0.0014286]]], "zero_fnc_remoteExecuteCommand", zero_var_HC1_owner] call zero_fnc_sendPacket;
 waitUntil {!isNil "zero_var_createMarkerResponse"};
 _marker = zero_var_createMarkerResponse;
 zero_var_createMarkerResponse = nil;
 _marker setMarkerColor "ColorYellow";
 _marker setMarkerText "!ACHTUNG! Angriff !ACHTUNG!";
 _marker setMarkerType "mil_warning";
 };
 _announce = zero_gang_flag getVariable "zero_var_gangAnnounce";
 _gangs = format["<t size='0.9px'>Folgende Gangs sind beteiligt:</t><br/>"];
 if(!((_announce select 1) isEqualTo [])) then { { if(!isNull _x && count (units _x) > 0) then { _gangs = _gangs + format["%1<br/>", (_x getVariable["zero_var_gang",[nil,""]]) select 1];
 };
 } forEach (_announce select 1);
 };
 [_gangs,2,"Der Kampf beginnt!"] call zero_fnc_msg;
 titleText ["Der Kampf beginnt!","PLAIN"];
 zero_gang_flag setVariable["zero_var_gangFight",serverTime,true];

[10] spawn zero_fnc_gangEroberungTimer;
 }else{ if((zero_gang_flag getVariable["zero_var_gangControl","-1"]) != (((group player) getVariable["zero_var_gang",["-1"]]) select 0)) then { ["Deine Gang hat den Kampf um die Gangeroberung verloren!",2,"Die Kampfhandlungen sind einzustellen!"] call zero_fnc_msg;
 titleText ["Deine Gang hat den Kampf um die Gangeroberung verloren!","PLAIN"];
 uiSleep random(1);
 if((group player) getVariable["zero_var_gangAnnounce",false]) then { (group player) setVariable["zero_var_gangAnnounce",nil,true];
 };
 uiSleep random(1);
 if(!(zero_gang_flag getVariable["zero_var_gangFightEnded",false])) then { zero_gang_flag setVariable["zero_var_gangFightEnded",true,true];
 zero_gang_flag setVariable["zero_var_gangFight",nil,true];
 zero_gang_flag setVariable["zero_var_gangAnnounce",nil,true];
 (group player) setVariable["zero_var_gangAnnounce",nil,true];
 deleteMarker "gang_angriff";
 };
 }else{ ["Deine Gang hat den Kampf um die Gangeroberung gewonnen!",2,"Du kannst nun die Vorteile nutzen!"] call zero_fnc_msg;
 titleText ["Deine Gang hat den Kampf um die Gangeroberung gewonnen!","PLAIN"];
 uiSleep random(1);
 if(!(zero_gang_flag getVariable["zero_var_gangFightEnded",false])) then { zero_gang_flag setVariable["zero_var_gangFightEnded",true,true];
 zero_gang_flag setVariable["zero_var_gangFight",nil,true];
 zero_gang_flag setVariable["zero_var_gangAnnounce",nil,true];
 (group player) setVariable["zero_var_gangAnnounce",nil,true];
 zero_gang_flag setVariable["zero_var_gangControlGroup",(group player), true];
 deleteMarker "gang_angriff";
 [[group player],"zero_fnc_insertrandomBuff",zero_var_hc1_owner,false] call zero_fnc_sendPacket;
 [(((group player) getVariable["zero_var_gang",["-1"]]) select 0),"zero_fnc_updateGangeroberung",zero_var_HC1_owner] call zero_fnc_sendPacket;
 };
 uiSleep random(1);
 if((group player) getVariable["zero_var_gangAnnounce",false]) then { (group player) setVariable["zero_var_gangAnnounce",nil,true];
 };
 };
 };

