if(!hasInterface) exitWith {};
 if(playerSide isEqualTo west || playerSide isEqualTo independent) exitWith {};
 if(!isNull (objectParent player)) exitWith {(localize "STR_NOTF_VehicleGetOut") call zero_fnc_msg;
};
 if(player getVariable["zero_var_restrained",false]) exitWith {(localize "STR_General_Zipties_Error") call zero_fnc_msg;
};
 private _fnc_getMoney = { params[["_isUnidentifiable",false,[false]]];
 private _rnd = round(random(100));
 private _res = 100000;
 if(_isUnidentifiable) then { switch (true) do { case(_rnd < 10): {_res = _res + round(random(100000));
};
 case(_rnd >= 10 && _rnd < 60): {_res = _res + 100000 + round(random(175000));
};
 case(_rnd >= 60 && _rnd < 95): {_res = _res + 250000 + round(random(300000));
};
 case(_rnd >= 95): {_res = _res + 400000 + round(random(350000));
};
 };
 }else{ switch (true) do { case(_rnd < 25): {_res = _res + round(random(75000));
};
 case(_rnd >= 25 && _rnd < 75): {_res = _res + 50000 + round(random(200000));
};
 case(_rnd >= 75): {_res = _res + 150000 + round(random(400000));
};
 };
 };
 _res };
 private _price = 0;
 private _hasSold = true;
 while {_hasSold} do { _hasSold = false;
 if([false,"artifact_worthless",1] call zero_fnc_handleZOInv) then { _price = _price + ([] call _fnc_getMoney);
 _hasSold = true;
 [format ["ITEM SELL: %1 (%2, %3) hat 1 Wertloses Artefakt verkauft => %4",player getVariable["zero_var_realname",name player], getPlayerUID player, playerSide, _price]] call zero_fnc_zoLog;

};
 if([false,"artifact_minor",1] call zero_fnc_handleZOInv) then { _price = _price + ([] call _fnc_getMoney);
 _hasSold = true;
 [format ["ITEM SELL: %1 (%2, %3) hat 1 Minderes Artefakt verkauft => %4",player getVariable["zero_var_realname",name player], getPlayerUID player, playerSide, _price]] call zero_fnc_zoLog;
 };
 if([false,"artifact_unidentifiable",1] call zero_fnc_handleZOInv) then { _price = _price + ([true] call _fnc_getMoney);
 _hasSold = true;
 [format ["ITEM SELL: %1 (%2, %3) hat 1 Unidentifizierbares Artefakt verkauft => %4",player getVariable["zero_var_realname",name player], getPlayerUID player, playerSide, _price]] call zero_fnc_zoLog;
 };
 if([false,"artifact_unique",1] call zero_fnc_handleZOInv) then { _price = _price + ([] call _fnc_getMoney);
 _hasSold = true;
 [format ["ITEM SELL: %1 (%2, %3) hat 1 Ungewöhnliches Artefakt verkauft => %4",player getVariable["zero_var_realname",name player], getPlayerUID player, playerSide, _price]] call zero_fnc_zoLog;
 };
 if([false,"artifact_valuable",1] call zero_fnc_handleZOInv) then { _price = _price + ([] call _fnc_getMoney);
 _hasSold = true;
 [format ["ITEM SELL: %1 (%2, %3) hat 1 Wertvolles Artefakt verkauft => %4",player getVariable["zero_var_realname",name player], getPlayerUID player, playerSide, _price]] call zero_fnc_zoLog;
 };
 };
 if(_price isEqualTo 0) exitWith {"Du hast keine Artifakte dabei" call zero_fnc_msg;
};
 [format["Du hast insgesamt %1€ erhalten",[_price] call zero_fnc_numberText],1] call zero_fnc_msg;
 [1, ([3, 0] call zero_fnc_Z0Check) + _price] call zero_fnc_Z0Check;

